name: Push Image to Docker Hub (Dev env)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/saleor-backend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/saleor-backend:${{ github.ref_name }}
          # platforms: linux/amd64,linux/arm64

      - name: Verify
        run: echo ${{ steps.buildx.outputs.digest }}